html tamplate
Bezart/global-talk-template pull request #1
Opened 2023-02-04 21:36 UTC by Snizhana-Uzumaki

2023-02-08 22:06 UTC, Snizhana-Uzumaki commented
Finish task

2023-02-09 09:06 UTC, Snizhana-Uzumaki commented
Fix padding

2023-02-09 10:58 UTC, Bezart commented on home_page.html
> +                    <p class="meaning-platform">E-COURSE PLATFORM</p>
Currently "Montserrat" font family is not applied to this paragraph as well as font-weight

2023-02-09 10:59 UTC, Bezart commented on home_page.html
> +    <header class="site-navigation">
The header height is much larger than in the mock-up

2023-02-09 11:07 UTC, Bezart commented on style.css
> +        /*button*/
Check the values of these variables. You misspelled "px" and  it breaks a lot of elements on the page

2023-02-09 11:10 UTC, Bezart commented on home_page.html
> +    <section class="ad-info">
What is "ad"? This term is usually means "advertisement" and indicates content that is not part of the website but rather third party promotional blocks. I would recommend naming this block differently

2023-02-09 11:11 UTC, Bezart commented on home_page.html
> +    <title>global-talk-templat</title>
Please use the "readable" title, it should be clear  for users what site they are looking at.

2023-02-09 11:12 UTC, Bezart commented on home_page.html
> +                            <p class="sprint-name" >Sprint →</p>
For arrows, don't just insert symbol, but use an html character code instead

2023-02-09 11:14 UTC, Bezart commented on style.css
> +        --padding-seven: 84px 30.5px 14px 30.5px;
Never use half pixel values. If you see this in the mock-up, it is a mistake

2023-02-09 12:41 UTC, Bezart commented on style.css
> +    /*Padding*/
It is not the best way to define paddings variables. Try to define the scale order, e.g.:

spacing-xxs: 2px
spacing-xs: 4px
spacing-s: 8px
spacing-m: 16px
....

Than use those tokens separately
padding: spacing-s
padding-right: spacing-m
...
etc

Not every padding value should be a variable

2023-02-09 12:43 UTC, Bezart requested changes
@Snizhana-Uzumaki please check my comments and read the guide how to add descriptions to pull requests https://infinum.com/blog/write-good-pull-requests/

2023-02-13 10:45 UTC, closed without merging